### PR TITLE
remove bundled gnugo.el

### PR DESCRIPTION
**Pull request by tarsius**
A more recent version of `gnugo` is now available from GNU Elpa.  It
should not be tracked in this repository also, because otherwise adding
"back-ends/" to the `load-path` (to get the other backends), might mean
that an outdated `gnugo.el` gets loaded.

### CODE REVIEW

**Comment by tarsius** [comment]
https://github.com/milkypostman/melpa/pull/3517

**Comment by tarsius** [comment]
What are the odds that you are going to merge this?

**Comment by eschulte** [comment]
Sorry, I've been letting everything here languish recently.

**Comment by tarsius** [comment]
That happens, no problem. Thanks for the merge!

**Comment by tarsius** [comment]
(note to self) This was reverted again in ff45fb44d9cb6579d8511d8b6156ed0b34d5ac97.

**Pull request merged**
